---
apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-server-service
  labels:
    app: rest-proxy
spec:
  ports:
    - port: 80
      name: https
      targetPort: 80
  type: LoadBalancer
  selector:
    app: rest-proxy

